<?php

namespace LouvreBundle\Repository;

/**
 * BilletsOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletsOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
