<?php

namespace LouvreBundle\Repository;

/**
 * TicketsCollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketsCollectionRepository extends \Doctrine\ORM\EntityRepository
{
}
